# Site settings
author: Michaelle Barbor
title: 
header-img: img/home-bg.png
email: michaelle.barbor@outlook.com
copyright_name: Michaelle Barbor
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Mika-byte

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
